In [17]:
import numpy as np

In [31]:
#Defining functions
def sigmoid(z):
    return 1/(1+np.exp(-z))

def sigmoid_derivative(z):
    return np.multiply(sigmoid(z), sigmoid(1.0-z))

def func(a):

    theta1=2*np.random.random([2,3])*a - a

    theta2=2*np.random.random([1,3])*a - a

    theta1=np.mat(theta1)#converting into matrix
    theta2=np.mat(theta2)

    return theta1,theta2

def fit_func(X, Y, theta1,theta2, predict=False, x=None):
    
    grad1=np.mat(np.zeros(np.shape(theta1)))
    
    grad2=np.mat(np.zeros(np.shape(theta2)))

    for i in range(len(X)):
        x = x if predict else X[i]
        y = Y[0,i]
        a=x
        a1=np.mat(np.append(1, x)).T
        z2=theta1*a1
        a2=sigmoid(z2)
        a2=np.mat(np.append(1, a2)).T
        z3=theta2*a2
        a3=sigmoid(z3)

        if predict: 
            return a3
   
       #Gradient Descnt

        del3 = a3 - y.T
        grad2 += del3 * a2.T
        del2 = np.multiply(theta2.T*del3, sigmoid_derivative(a2))
        grad1 += (del2[1:] * a1.T)

    return grad1,grad2


def predict(x):
    return fit_func(X, Y, theta1,theta2, True, x)


X = np.mat([[0,0],
            [0,1],
            [1,0],
            [1,1]])

Y = np.mat([0,1,1,0])

epochs = 10000
l_r = 0.95  #learning rate
a = 1  #norm_

theta1,theta2 = func(a)

for i in range(epochs):
    g1,g2 = fit_func(X, Y, theta1,theta2)

    theta1 -= l_r * g1  #Updating values
    theta2 -= l_r * g2



for i in range(len(X)):
    x = X[i]
    print(x, ":", predict(x))

[[0 0]] : [[0.00166615]]
[[0 1]] : [[0.99839415]]
[[1 0]] : [[0.99839371]]
[[1 1]] : [[0.00166614]]
